[toolchain]
anchor_version = "0.29.0"

[features]
seeds = true
skip-lint = false

[programs.localnet]
referrerstorage = "6RbbdFjmhqPiQ3bqk8Gg8StwJ7szwPPGAzjRLmeFLC7D"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
# cluster = "devnet"
# cluster = "testnet"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
