[toolchain]
anchor_version = "0.29.0"

[features]
seeds = true
skip-lint = false

[programs.localnet]
bondcurve = "7yx8TskMu1CD9pfxJGH3AEwEP7SGhNyt8nwiEvgus5zQ"

[programs.devnet]
bondcurve = "7yx8TskMu1CD9pfxJGH3AEwEP7SGhNyt8nwiEvgus5zQ"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "external-programs/mpl_token_metadata.so"     #

[[test.genesis]]
address = "CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C"
program = "external-programs/cpmm.so"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "Localnet"
cluster = "devnet"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
create = "npx ts-node tests/create.ts"
read = "npx ts-node tests/read.ts"

[test.validator]
url = "https://api.mainnet-beta.solana.com"
# url = "https://rpc.asdf1234.win"

# cp-swap program in mainnet
[[test.validator.clone]]
address = "CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C"

# cp-swap create_pool_fee_reveiver in mainnet
[[test.validator.clone]]
address = "DNXgeM9EiiaAbaWvwjHj9fQQLAX5ZsfHyvmYUNRAdNC8"

# cp-swap ammConfig in mainnet
[[test.validator.clone]]
address = "D4FPEruKEHrG5TenZ2mpDGEfu1iUvTiqBxvpU8HLBvC2"
